await import('./run.mjs');
if(process.exitCode)process.exit(process.exitCode);
await import('./boundaries.mjs');
if(process.exitCode)process.exit(process.exitCode);
await import('./age-capacity.mjs');
await import('./rounding.mjs');
await import('./sbpe.mjs');
await import('./matrix.mjs');
await import('./centavos.mjs');
await import('./payment-cap.mjs');
